name: Build and Deploy Production

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize', 'closed']
    branches: ['main']

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    env:
      VITE_API: ${{ secrets.VITE_API }}

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Run Unit tests
        run: npm run test
      - name: Run Unit tests coverage
        run: npx vitest --coverage
      - name: Report Unit tests coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.1.0
      - name: Build
        run: npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

    outputs:
      status: ${{ job.status }}
